CREATE SCHEMA IF NOT EXISTS order_service;

CREATE TABLE order_service.platform_order(
    ORDER_ID UUID NOT NULL,
    PRODUCT_ID UUID NOT NULL,
    QUANTITY INT NOT NULL,
    CONSTRAINT PK_PLATFORM_ORDER PRIMARY KEY (ORDER_ID)
);

CREATE TABLE order_service.platform_product(
    PRODUCT_ID UUID NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    STOCK INT NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    CONSTRAINT PK_PLATFORM_PRODUCT PRIMARY KEY (PRODUCT_ID)
);
ALTER TABLE order_service.platform_order ADD
CONSTRAINT FK_PLATFORM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES order_service.platform_product(PRODUCT_ID);
