version: '3.8'
services:
  user-service-db:
    container_name: user_service_db
    image: postgres:17
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: userserviceadmin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pl_user_service